# Generated by Django 5.0.6 on 2024-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
                ('category', models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza')], max_length=255)),
                ('info', models.TextField()),
            ],
        ),
    ]
