# Generated by Django 5.0.6 on 2024-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('biryani', 'Biryani'), ('noodles', 'Noodles'), ('cake', 'Cake')], max_length=255),
        ),
    ]
