# Generated by Django 5.0.6 on 2024-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('biryani', 'Biryani'), ('noodles', 'Noodles'), ('cake', 'Cake'), ('momos', 'Momos'), ('ice cream', 'Ice cream'), ('shakes', 'Shakes'), ('northfood', 'Northfood'), ('southfood', 'Southfood')], max_length=255),
        ),
    ]
