# Generated by Django 5.0.6 on 2024-07-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('cart', models.JSONField()),
                ('wishList', models.JSONField()),
            ],
        ),
    ]
