# Generated by Django 5.0.6 on 2024-07-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='users',
            name='wishList',
        ),
    ]
