# Generated by Django 5.0.6 on 2024-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_users_cart_remove_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(default='sample@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='Mumbai', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default=9022428111, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(default='9022428111', max_length=20),
            preserve_default=False,
        ),
    ]
